=== OP-TED/model2owl/xspec/test/win-bats/collection.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" targetNamespace="x-urn:xspec:test:xspec-bat"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xspec-bat="x-urn:xspec:test:xspec-bat">

	<xs:import namespace="http://www.w3.org/XML/1998/namespace"
		schemaLocation="http://www.w3.org/2001/xml.xsd" />

	<xs:element name="collection" type="xspec-bat:collectionType">
		<xs:key name="caseId">
			<xs:selector xpath="xspec-bat:case" />
			<xs:field xpath="@name" />
		</xs:key>
	</xs:element>

	<xs:complexType name="collectionType">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" name="case">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xspec-bat:scriptString">
							<xs:attribute name="name" type="xspec-bat:nameString" use="required" />
							<xs:attribute name="ifdef" type="xs:NMTOKENS" />
							<xs:attribute fixed="preserve" ref="xml:space" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="nameString">
		<xs:restriction base="xs:string">
			<xs:pattern value="\S.*\S" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="scriptString">
		<xs:restriction base="xs:string">
			<!-- [\s\S]* is to allow line breaks -->
			<xs:pattern value="[\s\S]*\scall\s+:verify_\S+[\s\S]*" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== OP-TED/model2owl/xspec/test/win-bats/collection.xml
<?xml version="1.0" encoding="UTF-8"?>
<collection xmlns="x-urn:xspec:test:xspec-bat" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="x-urn:xspec:test:xspec-bat collection.xsd">

	<!--
		Usage (CLI)
	-->

	<case name="invoking xspec without arguments prints usage">
    call :run ..\bin\xspec.bat
    call :verify_retval 1
    call :verify_line 3 x "Usage: xspec [-t|-q|-s|-c|-j|-catalog file|-e|-h] file"
	</case>

	<case name="invoking xspec without arguments prints usage even if Saxon environment variables are not defined">
    set SAXON_CP=
    call :run ..\bin\xspec.bat
    call :verify_retval 1
    call :verify_line 1 x "SAXON_CP and SAXON_HOME both not set!"
    call :verify_line 4 r "Usage: xspec "
	</case>

	<case name="invoking xspec with -h prints usage and does so even when it is 11th argument">
    call :run ..\bin\xspec.bat -t -t -t -t -t -t -t -t -t -t -h
    call :verify_retval 0
    call :verify_line 1 r "Usage: xspec "
	</case>

	<case name="invoking xspec with unknown option prints usage">
    call :run ..\bin\xspec.bat -bogus ..\tutorial\escape-for-regex.xspec
    call :verify_retval 1
    call :verify_line 1 x "Error: Unknown option: -bogus"
    call :verify_line 3 r "Usage: xspec "
	</case>

	<case name="invoking xspec with extra arguments prints usage">
    call :run ..\bin\xspec.bat ..\tutorial\escape-for-regex.xspec bogus
    call :verify_retval 1
    call :verify_line 1 x "Error: Extra option: bogus"
    call :verify_line 3 r "Usage: xspec "
	</case>

	<!--
		Mutually exclusive test types (CLI)
	-->

	<case name="invoking xspec with -s and -t prints error message">
    call :run ..\bin\xspec.bat -s -t
    call :verify_retval 1
    call :verify_line 1 x "-s and -t are mutually exclusive"
	</case>

	<case name="invoking xspec with -s and -q prints error message">
    call :run ..\bin\xspec.bat -s -q
    call :verify_retval 1
    call :verify_line 1 x "-s and -q are mutually exclusive"
	</case>

	<case name="invoking xspec with -t and -q prints error message">
    call :run ..\bin\xspec.bat -t -q
    call :verify_retval 1
    call :verify_line 1 x "-t and -q are mutually exclusive"
	</case>

	<!--
		XSPEC_HOME
	-->

	<case name="XSPEC_HOME">
    set "XSPEC_HOME=%PARENT_DIR_ABS%"

    cd /d "%WORK_DIR%"

    call :copy "%XSPEC_HOME%\bin\xspec.bat" my-xspec.bat

    call :run my-xspec.bat "%XSPEC_HOME%\tutorial\escape-for-regex.xspec"
    call :verify_retval 0
    call :verify_line 22 x "passed: 5 / pending: 0 / failed: 1 / total: 6"
    call :verify_line 23 x "Report available at %TEST_DIR%\escape-for-regex-result.html"
	</case>

	<case name="XSPEC_HOME is not a directory">
    set "XSPEC_HOME=%WORK_DIR%\file %RANDOM%"
    call :copy NUL "%XSPEC_HOME%"

    call :run ..\bin\xspec.bat ..\tutorial\escape-for-regex.xspec
    call :verify_retval 1
    call :verify_line 1 x "ERROR: XSPEC_HOME is not a directory: %XSPEC_HOME%"
	</case>

	<case name="XSPEC_HOME seems to be corrupted">
    set "XSPEC_HOME=%WORK_DIR%"

    call :run ..\bin\xspec.bat ..\tutorial\escape-for-regex.xspec
    call :verify_retval 1
    call :verify_line 1 x "ERROR: XSPEC_HOME seems to be corrupted: %XSPEC_HOME%"
	</case>

	<case name="cd to bin dir and run CLI from there using implicit XSPEC_HOME #1568">
    cd ..\bin
    call :run xspec.bat ..\tutorial\escape-for-regex.xspec
    call :verify_retval 0
    call :verify_line 22 x "passed: 5 / pending: 0 / failed: 1 / total: 6"
    call :verify_line 23 x "Report available at %TEST_DIR%\escape-for-regex-result.html"
	</case>

	<!--
		SAXON_CP has precedence over SAXON_HOME
	-->

	<case name="SAXON_CP has precedence over SAXON_HOME">
    set "SAXON_HOME=%WORK_DIR%\empty-saxon-home %RANDOM%"
    call :mkdir "%SAXON_HOME%"

    call :run ..\bin\xspec.bat ..\tutorial\escape-for-regex.xspec
    call :verify_retval 0
	</case>

	<!--
		Coverage (CLI)
	-->

	<case ifdef="XSLT_SUPPORTS_COVERAGE" name="invoking xspec -c creates report files">
    rem Other stderr #204
    set JAVA_TOOL_OPTIONS=-Dfoo

    rem Non alphanumeric path #208
    set "SPECIAL_CHARS_DIR=%WORK_DIR%\up &amp; down %RANDOM%"
    call :mkdir "%SPECIAL_CHARS_DIR%"

    call :copy ..\tutorial\coverage\demo* "%SPECIAL_CHARS_DIR%"
    set TEST_DIR=

    call :run ..\bin\xspec.bat -c "%SPECIAL_CHARS_DIR%\demo.xspec"
    call :verify_retval 0

    rem XML and HTML report file
    call :verify_exist "%SPECIAL_CHARS_DIR%\xspec\demo-result.xml"
    call :verify_exist "%SPECIAL_CHARS_DIR%\xspec\demo-result.html"

    rem Check the coverage trace XML file contents
    call :run java -jar "%SAXON_JAR%" ^
        -s:"%SPECIAL_CHARS_DIR%\xspec\demo-coverage.xml" ^
        -xsl:check-coverage-xml.xsl
    call :verify_retval 0
    call :verify_line 1 x "true"

    rem Coverage report HTML file is created and contains CSS inline #194
    call :run java -jar "%SAXON_JAR%" -s:"%SPECIAL_CHARS_DIR%\xspec\demo-coverage.html" -xsl:check-html-css.xsl
    call :verify_retval 0
    call :verify_line 1 x "true"
	</case>

	<case name="invoking xspec -c -q prints error message">
    call :run ..\bin\xspec.bat -c -q ..\tutorial\xquery-tutorial.xspec
    call :verify_retval 1
    call :verify_line 1 x "Coverage is supported only for XSLT"
	</case>

	<case name="invoking xspec -c -s prints error message">
    call :run ..\bin\xspec.bat -c -s ..\tutorial\schematron\demo-01.xspec
    call :verify_retval 1
    call :verify_line 1 x "Coverage is supported only for XSLT"
	</case>

	<!--
		CLI without TEST_DIR
	-->

	<case name="invoking xspec without TEST_DIR set externally (XSLT)">
    set TEST_DIR=

    rem Use a fresh dir, to make the message line numbers predictable
    rem and to avoid a residue of output files
    set "TEST_COPY=%WORK_DIR%\some-failures %RANDOM%"
    call :mkdir "%TEST_COPY%"
    call :copy some-failures\function.* "%TEST_COPY%"

    rem Run
    call :run ..\bin\xspec.bat "%TEST_COPY%\function.xspec"

    rem By default, failure is not error
    call :verify_retval 0

    rem Verify message
    call :verify_line 16 x "passed: 1 / pending: 0 / failed: 2 / total: 3"
    call :verify_line 17 x "Report available at %TEST_COPY%\xspec\function-result.html"
    call :verify_line 18 x "Done."

    rem Verify report files
    rem * XML report file is created
    rem * HTML report file is created
    rem * Coverage is disabled by default
    rem * JUnit is disabled by default
    call :run dir /b /o:n "%TEST_COPY%\xspec"
    call :verify_line_count 3
    call :verify_line 1 x function-compiled.xsl
    call :verify_line 2 x function-result.html
    call :verify_line 3 x function-result.xml

    rem HTML report file contains CSS inline #135
    call :run java -jar "%SAXON_JAR%" ^
        -s:"%TEST_COPY%\xspec\function-result.html" ^
        -xsl:check-html-css.xsl
    call :verify_retval 0
    call :verify_line 1 x "true"
	</case>

	<case ifdef="XSLT_SUPPORTS_COVERAGE" name="invoking xspec -c without TEST_DIR set externally">
    set TEST_DIR=

    rem Use a fresh dir, to make the message line numbers predictable
    rem and to avoid a residue of output files
    set "TEST_COPY=%WORK_DIR%\some-failures %RANDOM%"
    call :mkdir "%TEST_COPY%"
    call :copy some-failures\function.* "%TEST_COPY%"

    rem Run
    call :run ..\bin\xspec.bat -c "%TEST_COPY%\function.xspec"

    rem By default, failure is not error
    call :verify_retval 0

    rem Verify message
    call :verify_line 19 x "passed: 1 / pending: 0 / failed: 2 / total: 3"
    call :verify_line 22 x "Report available at %TEST_COPY%\xspec\function-coverage.html"
    call :verify_line 23 x "Done."

    rem Verify report files
    rem * XML report file is created
    rem * HTML report file is created
    rem * Coverage XML report is created
    rem * Coverage HTML report is created
    rem * JUnit is disabled by default
    call :run dir /b /o:n "%TEST_COPY%\xspec"
    call :verify_line_count 5
    call :verify_line 1 x function-compiled.xsl
    call :verify_line 2 x function-coverage.html
    call :verify_line 3 x function-coverage.xml
    call :verify_line 4 x function-result.html
    call :verify_line 5 x function-result.xml
	</case>

	<case name="invoking xspec without TEST_DIR set externally (XQuery)">
    set TEST_DIR=

    rem Use a fresh dir, to make the message line numbers predictable
    rem and to avoid a residue of output files
    set "TEST_COPY=%WORK_DIR%\some-failures %RANDOM%"
    call :mkdir "%TEST_COPY%"
    call :copy some-failures\function.* "%TEST_COPY%"

    rem Run
    call :run ..\bin\xspec.bat -q "%TEST_COPY%\function.xspec"

    rem By default, failure is not error
    call :verify_retval 0

    rem Verify message
    call :verify_line  9 x "passed: 1 / pending: 0 / failed: 2 / total: 3"
    call :verify_line 10 x "Report available at %TEST_COPY%\xspec\function-result.html"
    call :verify_line 11 x "Done."

    rem Verify report files
    rem * XML report file is created
    rem * HTML report file is created
    rem * JUnit is disabled by default
    call :run dir /b /o:n "%TEST_COPY%\xspec"
    call :verify_line_count 3
    call :verify_line 1 x function-compiled.xq
    call :verify_line 2 x function-result.html
    call :verify_line 3 x function-result.xml
	</case>

	<case name="invoking xspec without TEST_DIR set externally (Schematron)">
    set TEST_DIR=

    rem Use a fresh dir, to make the message line numbers predictable
    rem and to avoid a residue of output files
    set "TEST_COPY=%WORK_DIR%\some-failures %RANDOM%"
    call :mkdir "%TEST_COPY%"
    call :copy some-failures\schematron.* "%TEST_COPY%"

    rem Run
    call :run ..\bin\xspec.bat -s "%TEST_COPY%\schematron.xspec"

    rem By default, failure is not error
    call :verify_retval 0

    rem Verify message
    rem * No Schematron warnings #129 #131
    call :verify_line  6 x "Converting Schematron XSpec into XSLT XSpec..."
    call :verify_line 21 x "passed: 1 / pending: 0 / failed: 2 / total: 3"
